# Generated by Django 4.2.2 on 2023-06-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productbrandmodel_title_and_more'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usercartmodel',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='UserCartModel_products', to='products.productmainmodel'),
        ),
        migrations.AlterField(
            model_name='userwishlistmodel',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='UserWishListModel_products', to='products.productmainmodel'),
        ),
    ]
