# Generated by Django 4.2.2 on 2023-06-22 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserProfileModel_cart', to='userprofile.usercartmodel'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='wishlist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserProfileModel_wishlist', to='userprofile.userwishlistmodel'),
        ),
    ]
