# Generated by Django 4.2.2 on 2023-06-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('INPROGRESS', 'INPROGRESS'), ('DECLINED', 'DECLINED'), ('CANCELED', 'CANCELED'), ('COMPLETED', 'COMPLETED'), ('SHIPPED', 'SHIPPED'), ('DISPATCHED', 'DISPATCHED'), ('OUT_FOR_DELIVERY', 'OUT_FOR_DELIVERY')], default='INPROGRESS', max_length=50)),
                ('date_of_order', models.DateTimeField(blank=True, null=True)),
                ('date_of_delivery', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetailModel',
            fields=[
                ('transcation_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_code', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('CASH_ON_DELIVERY', 'CASH_ON_DELIVERY'), ('DEBIT/CREDIT_CART', 'DEBIT/CREDIT_CART'), ('UPI', 'UPI')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
