# Generated by Django 4.2.2 on 2023-06-19 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_productbrandmodel_title_and_more'),
        ('userprofile', '0002_userprofilemodel_gender_alter_usercartmodel_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetailModel',
            fields=[
                ('transcation_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_code', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('CASH_ON_DELIVERY', 'CASH_ON_DELIVERY'), ('DEBIT/CREDIT_CART', 'DEBIT/CREDIT_CART'), ('UPI', 'UPI')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('INPROGRESS', 'INPROGRESS'), ('DECLINED', 'DECLINED'), ('CANCELED', 'CANCELED'), ('COMPLETED', 'COMPLETED'), ('SHIPPED', 'SHIPPED'), ('DISPATCHED', 'DISPATCHED'), ('OUT_FOR_DELIVERY', 'OUT_FOR_DELIVERY')], default='INPROGRESS', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrderModel_address', to='userprofile.useraddressmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderModel_product', to='products.productmainmodel')),
            ],
        ),
    ]
